### ISSUE TITLE
fs.extra module?

### ISSUE THREAD

**Issue by wrought** [sudomesh/makenode#13]
I cloned the repo from scratch (just now), ran `npm install` but no dice on the fs.extra issue...

```
$ ./makenode.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'fs.extra'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/wrought/projects/makenode/u.js:2:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by wrought** [comment]
Ah, it was a typo. patched.

**Comment by max-b** [comment]
Thanks - I replaced `fs.extra` with `fs-extra` in makenode.js and forgot to switch it in `u.js`.
